import { includeHTML } from "./include.js";

includeHTML("/guide/heading.html", "#heading");
includeHTML("/guide/text.html", "#text");
includeHTML("/guide/link.html", "#link");
includeHTML("/guide/button.html", "#button");
includeHTML("/guide/input.html", "#input");
includeHTML("/guide/textarea.html", "#textarea");
includeHTML("/guide/select.html", "#select");
includeHTML("/guide/switch.html", "#switch");
includeHTML("/guide/radio.html", "#radio");
includeHTML("/guide/checkbox.html", "#checkbox");
includeHTML("/guide/chip.html", "#chip");
includeHTML("/guide/dialog.html", "#dialog");
includeHTML("/guide/gallery.html", "#gallery");
includeHTML("/guide/inputarea.html", "#inputarea");
includeHTML("/guide/recommended.html", "#recommended");
includeHTML("/guide/recentsearch.html", "#recentsearch");
includeHTML("/guide/xchip.html", "#xchip");
includeHTML("/guide/popularsearch.html", "#popularsearch");
includeHTML("/guide/menubar.html", "#menubar");
includeHTML("/guide/navigation.html", "#navigation");
includeHTML("/guide/recommendedsearch.html", "#recommendedsearch");
includeHTML("/guide/header.html", "#header");
